#pragma once

namespace ObjectState {
	enum OBJ_STATE {
		ALIVE,
		BURN,
		ACTIVE_DAMAGE,
		DIE,
	};
}

namespace Loader {
	enum OBJ_LOADED {
		BRICK,
		BRICK2,
		BRICK3,
		BRICK_FLAG,
		BRICK_INTRO,
		CANDLE,
		TORCH,
		DOOR,
		STAIR,
		GHOST,
		DOG,
		BAT,
		FISHMAN,
	};
}

namespace TeamType {
	enum TYPE {
		LEAGUE,
		ENEMY,
		ITEM,
		GROUND,
		STATIC,
		WEAPON,
		STAIR,
		DOOR
	};
}

enum OBJ_ID {
	OBJ_SIMON,
	OBJ_WEAPON_WHIP,
	OBJ_WEAPON_WHIP1,
	OBJ_WEAPON_WHIP2,
	OBJ_WEAPON_WHIP3,
	OBJ_SUBWEAPON_DAGGER,					 //id sprite
	OBJ_SUBWEAPON_AXE,					 // anim 
	OBJ_SUBWEAPON_HOLLYWATER,			//anim Holy
	OBJ_SUBWEAPON_BOOMERANG,				//anim
	OBJ_ENEMY_GHOST,						//anim
	OBJ_ENEMY_FIREBALL,					// spriteId
	OBJ_GROUND,
	OBJ_ITEM_SUBWEAPON_NULL,
	OBJ_ITEM_SMALLHEART,
	OBJ_ITEM_BIGHEART,
	OBJ_ITEM_MONEYBAG,
	OBJ_ITEM_MORNINGSTAR,
	OBJ_ITEM_DAGGER,
	OBJ_ITEM_CROSS,
	OBJ_ITEM_AXE,
	OBJ_ITEM_BOOMERANG,
	OBJ_ITEM_FIREBOMB,
	OBJ_ITEM_PORKCHOP,
	OBJ_ITEM_MAGICCRYSTAL,
	OBJ_STATIC_TORCH,
	OBJ_STATIC_CANDLE,
	OBJ_ITEM_STOPWATCH,
};